version: '3.8'

services:
  app:
    image: ghcr.io/saqibmehmood/jobops:efd6c3fe115cd6a1e8d38f12e0af027df6699950
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY=${SECRET_KEY}
      - DEBUG=${DEBUG}
      - ALLOWED_HOSTS=${ALLOWED_HOSTS}
      - DATABASE_NAME=jobops
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_HOST=db
      - DATABASE_PORT=5432
      - CELERY_BROKER_URL=redis://redis:6379/0
      - CELERY_RESULT_BACKEND=redis://redis:6379/0
    depends_on:
      - db
      - redis
    networks:
      - jobops-network

  db:
    image: postgres:13
    environment:
      - POSTGRES_DB=jobops
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jobops-network

  redis:
    image: redis:6
    ports:
      - "6380:6379"
    networks:
      - jobops-network

networks:
  jobops-network:
    driver: bridge

volumes:
  postgres_data:
