name: JobOps CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_DB: jobops
          POSTGRES_USER: jobops_user
          POSTGRES_PASSWORD: jobops_pass
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: jobops.settings
          SECRET_KEY: test-secret-key
          DEBUG: True
          DATABASE_NAME: jobops
          DATABASE_USER: postgres
          DATABASE_PASSWORD: postgres
          DATABASE_HOST: db
          DATABASE_PORT: 5432
          # Note: Uses PostgreSQL service for tests, matches settings.py
        run: |
          python manage.py test core.tests.UserModelTest

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          # GHCR_USERNAME: Your GitHub username (e.g., 'yourusername')
          # GHCR_TOKEN: GitHub PAT with 'write:packages' scope
          # Set in: Repo -> Settings -> Secrets and variables -> Actions
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/jobops:${{ github.sha }}
          # Replace 'yourusername' with your GitHub username (e.g., 'johndoe')