name: JobOps CI

on:
  push:
    branches:
      - dev

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run Django tests
        env:
          DJANGO_SETTINGS_MODULE: jobops.settings
          SECRET_KEY: test-secret-key
          DEBUG: True
          DATABASES: '{"default": {"ENGINE": "django.db.backends.sqlite3", "NAME": ":memory:"}}'
          # Forces SQLite for tests, no PostgreSQL/Redis
        run: |
          python manage.py test core.tests.UserModelTest

  build-and-push:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ secrets.GHCR_USERNAME }}
          password: ${{ secrets.GHCR_TOKEN }}
          # GHCR_USERNAME: Your GitHub username (e.g., 'yourusername')
          # GHCR_TOKEN: GitHub PAT with 'write:packages' scope
          # Set in: Repo -> Settings -> Secrets and variables -> Actions
      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/jobops:${{ github.sha }}
          # Replace 'yourusername' with your GitHub username (e.g., 'johndoe')